import os

# os.system("python train_auto_classification.py --dataset 'brain-tumor' --num-trials 25 2>&1 | tee log_brain_tumor_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'citrus-leaves' --num-trials 25 2>&1 | tee log_citrus_leaves_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'flower-10' --num-trials 25 2>&1 | tee log_flower_10_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'ibeans' --num-trials 25 2>&1 | tee log_ibeans_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'monkey-10' --num-trials 25 2>&1 | tee log_monkey_10_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'boat' --num-trials 25 2>&1 | tee log_boat_trials_25.txt")
# os.system("python train_auto_classification.py --dataset 'honey-bee' --num-trials 25 2>&1 | tee log_honey_bee_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'dtd' --num-trials 25 2>&1 | tee log_dtd_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'coil-100' --num-trials 25 2>&1 | tee log_coil_100_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'casting-products' --num-trials 25 2>&1 | tee log_casting_products_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'oregon-wildlife' --num-trials 25 2>&1 | tee log_oregon_wildlife_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'intel' --num-trials 25 2>&1 | tee log_intel_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'leaves' --num-trials 25 2>&1 | tee log_leaves_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'caltech-256' --num-trials 25 2>&1 | tee log_caltech_256_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'deep-weeds' --num-trials 25 2>&1 | tee log_deep_weeds_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'plant-village' --num-trials 25 2>&1 | tee log_plant_village_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'gender' --num-trials 25 2>&1 | tee log_gender_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'satelite-plane' --num-trials 25 2>&1 | tee log_satelite_plane_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'bird-225' --num-trials 25 2>&1 | tee log_bird_225_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'fruits-360' --num-trials 25 2>&1 | tee log_fruits_360_trials_25.txt")
os.system("python train_auto_classification.py --dataset 'green-finder' --num-trials 25 2>&1 | tee log_green_finder_trials_25.txt")
