import os

# os.system("python train_auto_ssd.py --dataset 'chess' --num-trials 25 2>&1 | tee log_ssd_chess_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'raccoon' --num-trials 25 2>&1 | tee log_ssd_raccoon_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'sheep' --num-trials 25 2>&1 | tee log_ssd_sheep_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'drone' --num-trials 25 2>&1 | tee log_ssd_drone_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'car-license-plates' --num-trials 25 2>&1 | tee log_ssd_car_license_plates_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'hands' --num-trials 25 2>&1 | tee log_ssd_hands_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'plant-doc' --num-trials 25 2>&1 | tee log_ssd_plant_doc_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'pets' --num-trials 25 2>&1 | tee log_ssd_pets_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'cars-and-traffic-signs' --num-trials 25 2>&1 | tee log_ssd_cars_and_traffic_signs_trials_25.txt")
# os.system("python train_auto_ssd.py --dataset 'stanford-dogs' --num-trials 25 2>&1 | tee log_ssd_stanford_dogs_trials_25.txt")

os.system("python train_auto_ssd.py --dataset 'chess' --num-trials 10 2>&1 | tee log_ssd_chess_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'raccoon' --num-trials 10 2>&1 | tee log_ssd_raccoon_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'sheep' --num-trials 10 2>&1 | tee log_ssd_sheep_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'drone' --num-trials 10 2>&1 | tee log_ssd_drone_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'car-license-plates' --num-trials 10 2>&1 | tee log_ssd_car_license_plates_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'hands' --num-trials 10 2>&1 | tee log_ssd_hands_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'plant-doc' --num-trials 10 2>&1 | tee log_ssd_plant_doc_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'pets' --num-trials 10 2>&1 | tee log_ssd_pets_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'cars-and-traffic-signs' --num-trials 10 2>&1 | tee log_ssd_cars_and_traffic_signs_trials_10.txt")
os.system("python train_auto_ssd.py --dataset 'stanford-dogs' --num-trials 10 2>&1 | tee log_ssd_stanford_dogs_trials_10.txt")
