training:
    random_seed: null
    batch_size: 64
    num_epochs: 100
    det_best_field: val_clip_score_at_1
    compute_clip_retrieval: true
    loss_cycle_cons: 0.001
net_video_pooler:
    name: atn
    output_dim: 384
    input_fc: true
    input_fc_output_dim: 384
    num_layers: 1
    num_heads: 8
    dropout: 0.05
    use_context: false
    pooler: atn
    atn_pool_dim: 768
    atn_pool_heads: 2
net_video_sequencer:
    name: atn
    output_dim: 384
    input_fc: false
    num_layers: 1
    num_heads: 8
    dropout: 0.05
    use_context: true
    atn_ctx_num_layers: 1
    atn_ctx_num_heads: 8
    pooler: avg
net_text_pooler:
    name: same
    same_as: net_video_pooler
net_text_sequencer:
    name: same
    same_as: net_video_sequencer
text_encoder:
    feature_dim: 1536
dataset:
    name: youcook2
    features: 100m
    train_split: train
    val_split: val
    max_frames: 80
    feature_dim: 512
    frames_noise: 0
    word_emb: bert
optimizer:
    name: radam
    lr: 0.0009
    weight_decay: 0
    momentum: 0.56
    adam_beta2: 0.98
    adam_eps: 1.5e-09
scheduler:
    patience: 5
    cooldown: 3
    warmup: 0