name: gluon_vision_docs
dependencies:
- python=3.7
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip=20.2
- pip:
  - https://github.com/mli/mx-theme/tarball/0.3.1
  - sphinx-gallery
  - mxnet
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
  - portalocker
  - decord
  - cython
  - pycocotools
  - autocfg
